//! Cross-checks the `journal` module against real `systemd-journal-remote`-produced fixtures
//! (registered in `forensic-testenv`'s `manifest/artifacts.toml`, generated by
//! `generators/journal.sh`/`journal_export.py`/`journal_unlink_entries.py`) and their
//! `journalctl --output=json` ground truth. Every `#[test]` here skips (not fails) when its
//! fixture isn't available locally — see the root `FINDINGS.md`'s "local-cache-index trick" for
//! running these without a Hugging Face publish.
#![cfg(feature = "journal")]

use frnsc_linux::journal::header;
use frnsc_linux::journal::reader::JournalFile;

fn read_bytes(path: std::path::PathBuf) -> Vec<u8> {
    std::fs::read(path).unwrap()
}

fn read_oracle(path: std::path::PathBuf) -> Vec<serde_json::Value> {
    let text = std::fs::read_to_string(path).unwrap();
    text.lines()
        .filter(|l| !l.trim().is_empty())
        .map(|l| serde_json::from_str(l).unwrap())
        .collect()
}

const GENEROUS_CAP: u64 = 256 * 1024 * 1024;

#[test]
fn plain_matches_oracle_entry_count_and_fields() {
    let data = read_bytes(forensic_testdata::artifact_or_skip!("linux-journal-plain-synthetic"));
    let oracle = read_oracle(forensic_testdata::artifact_or_skip!(
        "linux-journal-plain-synthetic-oracle"
    ));
    let journal = JournalFile::parse(data).unwrap();
    let result = journal.read_all(GENEROUS_CAP);
    let errs: Vec<_> = result.entries.iter().filter_map(|e| e.as_ref().err()).collect();
    assert!(errs.is_empty(), "unexpected errors: {errs:?}");
    let ok_entries: Vec<_> = result.entries.iter().filter_map(|e| e.as_ref().ok()).collect();
    assert_eq!(ok_entries.len(), oracle.len(), "entry count must match journalctl");
    for (entry, oracle_entry) in ok_entries.iter().zip(oracle.iter()) {
        let expected_message = oracle_entry["MESSAGE"].as_str().unwrap();
        let got_message = entry
            .fields
            .iter()
            .find(|f| f.raw_name == "MESSAGE")
            .and_then(|f| f.value_utf8.as_deref());
        assert_eq!(got_message, Some(expected_message));
        let expected_seqnum: u64 = oracle_entry["__SEQNUM"].as_str().unwrap().parse().unwrap();
        assert_eq!(entry.seqnum, expected_seqnum);
        let expected_realtime: u64 = oracle_entry["__REALTIME_TIMESTAMP"]
            .as_str()
            .unwrap()
            .parse()
            .unwrap();
        assert_eq!(entry.realtime, expected_realtime);
    }
    assert!(
        result.findings.is_empty(),
        "a clean plain file should have no integrity findings: {:?}",
        result.findings
    );
}

#[test]
fn uncompressed_matches_oracle() {
    let data = read_bytes(forensic_testdata::artifact_or_skip!(
        "linux-journal-uncompressed-synthetic"
    ));
    let oracle = read_oracle(forensic_testdata::artifact_or_skip!(
        "linux-journal-uncompressed-synthetic-oracle"
    ));
    let journal = JournalFile::parse(data).unwrap();
    let result = journal.read_all(GENEROUS_CAP);
    let errs: Vec<_> = result.entries.iter().filter_map(|e| e.as_ref().err()).collect();
    assert!(errs.is_empty(), "unexpected errors: {errs:?}");
    let ok_entries: Vec<_> = result.entries.iter().filter_map(|e| e.as_ref().ok()).collect();
    assert_eq!(ok_entries.len(), oracle.len(), "entry count");
    for (entry, oracle_entry) in ok_entries.iter().zip(oracle.iter()) {
        let expected_message = oracle_entry["MESSAGE"].as_str().unwrap();
        let got_message = entry
            .fields
            .iter()
            .find(|f| f.raw_name == "MESSAGE")
            .and_then(|f| f.value_utf8.as_deref());
        assert_eq!(got_message, Some(expected_message));
    }
    assert!(result.findings.is_empty(), "findings {:?}", result.findings);
}

#[test]
fn compressed_matches_oracle_and_decompresses_correctly() {
    let data = read_bytes(forensic_testdata::artifact_or_skip!(
        "linux-journal-compressed-synthetic"
    ));
    let oracle = read_oracle(forensic_testdata::artifact_or_skip!(
        "linux-journal-compressed-synthetic-oracle"
    ));
    let journal = JournalFile::parse(data).unwrap();
    assert!(
        journal.header().compression_codec().is_some(),
        "fixture should be compressed"
    );
    let result = journal.read_all(GENEROUS_CAP);
    let errs: Vec<_> = result.entries.iter().filter_map(|e| e.as_ref().err()).collect();
    assert!(errs.is_empty(), "unexpected errors: {errs:?}");
    let ok_entries: Vec<_> = result.entries.iter().filter_map(|e| e.as_ref().ok()).collect();
    assert_eq!(ok_entries.len(), oracle.len(), "entry count");
    for (entry, oracle_entry) in ok_entries.iter().zip(oracle.iter()) {
        let expected_message = oracle_entry["MESSAGE"].as_str().unwrap();
        let got_message = entry
            .fields
            .iter()
            .find(|f| f.raw_name == "MESSAGE")
            .and_then(|f| f.value_utf8.as_deref());
        assert_eq!(got_message, Some(expected_message));
    }
    assert!(result.findings.is_empty(), "findings {:?}", result.findings);
}

#[test]
fn compact_mode_parses() {
    let data = read_bytes(forensic_testdata::artifact_or_skip!("linux-journal-compact-synthetic"));
    let oracle = read_oracle(forensic_testdata::artifact_or_skip!(
        "linux-journal-compact-synthetic-oracle"
    ));
    let journal = JournalFile::parse(data).unwrap();
    assert!(journal.header().is_compact());
    let result = journal.read_all(GENEROUS_CAP);
    let errs: Vec<_> = result.entries.iter().filter_map(|e| e.as_ref().err()).collect();
    assert!(errs.is_empty(), "errors: {errs:?}");
    let ok_entries: Vec<_> = result.entries.iter().filter_map(|e| e.as_ref().ok()).collect();
    assert_eq!(ok_entries.len(), oracle.len());
    assert!(result.findings.is_empty(), "findings: {:?}", result.findings);
}

#[test]
fn keyed_hash_mode_parses_with_correct_hash_recompute() {
    let data = read_bytes(forensic_testdata::artifact_or_skip!(
        "linux-journal-keyed-hash-synthetic"
    ));
    let oracle = read_oracle(forensic_testdata::artifact_or_skip!(
        "linux-journal-keyed-hash-synthetic-oracle"
    ));
    let journal = JournalFile::parse(data).unwrap();
    assert!(journal.header().is_keyed_hash());
    let result = journal.read_all(GENEROUS_CAP);
    let errs: Vec<_> = result.entries.iter().filter_map(|e| e.as_ref().err()).collect();
    assert!(errs.is_empty(), "errors: {errs:?}");
    let ok_entries: Vec<_> = result.entries.iter().filter_map(|e| e.as_ref().ok()).collect();
    assert_eq!(ok_entries.len(), oracle.len());
    // The hash-recompute check specifically exercises siphash24 here (KEYED_HASH set); a clean
    // fixture must produce zero mismatches, which is the real cross-check that the hash function
    // itself is byte-exact (not just that the header flag was decoded correctly).
    assert!(
        result.findings.is_empty(),
        "findings (a siphash24 recompute mismatch would show here): {:?}",
        result.findings
    );
}

#[test]
fn online_stale_is_flagged() {
    let data = read_bytes(forensic_testdata::artifact_or_skip!(
        "linux-journal-online-stale-synthetic"
    ));
    let journal = JournalFile::parse(data).unwrap();
    assert_eq!(journal.header().state, header::State::Online);
    let result = journal.read_all(GENEROUS_CAP);
    assert!(
        result.findings.iter().any(|f| f.to_string().contains("ONLINE")),
        "findings: {:?}",
        result.findings
    );
}

#[test]
fn truncated_file_does_not_panic_and_reports_something() {
    let data = read_bytes(forensic_testdata::artifact_or_skip!("linux-journal-truncated-synthetic"));
    let journal = JournalFile::parse(data).unwrap();
    let result = journal.read_all(GENEROUS_CAP);
    // Reaching this line without a panic is the point; entries/findings content isn't asserted
    // beyond that, since a truncated file's exact recoverable content is inherently
    // implementation-shaped rather than something an external oracle defines.
    println!(
        "truncated: {} entries, {} findings",
        result.entries.len(),
        result.findings.len()
    );
}

#[test]
fn unlinked_entries_are_recovered_and_tagged() {
    let data = read_bytes(forensic_testdata::artifact_or_skip!(
        "linux-journal-unlinked-entries-synthetic"
    ));
    let oracle = read_oracle(forensic_testdata::artifact_or_skip!(
        "linux-journal-unlinked-entries-synthetic-oracle"
    ));
    let journal = JournalFile::parse(data).unwrap();
    let result = journal.read_all(GENEROUS_CAP);
    let ok_entries: Vec<_> = result.entries.iter().filter_map(|e| e.as_ref().ok()).collect();
    let indexed: Vec<_> = ok_entries.iter().filter(|e| !e.recovery_only).collect();
    let recovery_only: Vec<_> = ok_entries.iter().filter(|e| e.recovery_only).collect();
    assert_eq!(
        indexed.len(),
        oracle.len(),
        "indexed count must match journalctl's own (blind) count"
    );
    assert_eq!(recovery_only.len(), 1, "exactly one entry was unlinked from the tail");
    assert!(
        result
            .findings
            .iter()
            .any(|f| f.to_string().contains("recovery-scan-only")),
        "findings: {:?}",
        result.findings
    );
}

#[test]
fn non_utf8_message_is_kept_as_raw_bytes() {
    let data = read_bytes(forensic_testdata::artifact_or_skip!("linux-journal-non-utf8-synthetic"));
    let oracle = read_oracle(forensic_testdata::artifact_or_skip!(
        "linux-journal-non-utf8-synthetic-oracle"
    ));
    let journal = JournalFile::parse(data).unwrap();
    let result = journal.read_all(GENEROUS_CAP);
    let errs: Vec<_> = result.entries.iter().filter_map(|e| e.as_ref().err()).collect();
    assert!(errs.is_empty(), "errors: {errs:?}");
    let ok_entries: Vec<_> = result.entries.iter().filter_map(|e| e.as_ref().ok()).collect();
    let (idx, expected_bytes) = oracle
        .iter()
        .enumerate()
        .find_map(|(i, o)| {
            o["MESSAGE"]
                .as_array()
                .map(|arr| (i, arr.iter().map(|b| b.as_u64().unwrap() as u8).collect::<Vec<u8>>()))
        })
        .expect("oracle should have one non-utf8 MESSAGE entry");
    let entry = &ok_entries[idx];
    let message_field = entry.fields.iter().find(|f| f.raw_name == "MESSAGE").unwrap();
    assert!(
        message_field.value_utf8.is_none(),
        "a non-utf8 value must not be reported as valid utf8"
    );
    assert_eq!(message_field.value_raw, expected_bytes, "raw bytes must be kept exactly");
}

#[test]
fn zip_bomb_message_decompresses_within_a_generous_cap_and_does_not_panic() {
    let data = read_bytes(forensic_testdata::artifact_or_skip!("linux-journal-zip-bomb-synthetic"));
    let journal = JournalFile::parse(data).unwrap();
    let result = journal.read_all(GENEROUS_CAP); // above the real fixture's 64 MiB message
    let errs: Vec<_> = result.entries.iter().filter_map(|e| e.as_ref().err()).collect();
    assert!(errs.is_empty(), "errors: {errs:?}");
    let ok_entries: Vec<_> = result.entries.iter().filter_map(|e| e.as_ref().ok()).collect();
    assert_eq!(ok_entries.len(), 1);
    let message = ok_entries[0].fields.iter().find(|f| f.raw_name == "MESSAGE").unwrap();
    assert_eq!(message.value_raw.len(), 64 * 1024 * 1024);
}

#[test]
fn zip_bomb_message_is_rejected_under_a_small_cap_not_oom() {
    let data = read_bytes(forensic_testdata::artifact_or_skip!("linux-journal-zip-bomb-synthetic"));
    let journal = JournalFile::parse(data).unwrap();
    let result = journal.read_all(1024 * 1024); // 1 MiB cap, far under the real 64 MiB message
    let errs: Vec<_> = result.entries.iter().filter_map(|e| e.as_ref().err()).collect();
    assert!(!errs.is_empty(), "a payload exceeding the cap must be an Err, not silently truncated");
}
